package config

/*-------------------------------------------------------------------------------------------*/
//                                 DATABASE
/*-------------------------------------------------------------------------------------------*/
const DB_ADDRESS_FARM = "tbl_address_farm"
const DB_ADDRESS_USER = "tbl_address_user"
const DB_COUNTRY = "tbl_country"
const DB_DISTRICT = "tbl_district"
const DB_FARM = "tbl_farm"
const DB_FARM_AREA = "tbl_farm_area"
const DB_FAVORITE_PLANT = "tbl_favorite_plant"
const DB_FERTILIZER = "tbl_fertilizer"
const DB_FERTILIZER_CAT = "tbl_fertilizer_cat"
const DB_FORMULA_PLANT = "tbl_formula_plant"
const DB_FREQUENCY_TYPE = "tbl_frequency_type"
const DB_GENDER = "tbl_gender"
const DB_INDICATE_TYPE = "tbl_indicate_type"
const DB_MAINBOX = "tbl_mainbox"
const DB_PLANT = "tbl_plant"
const DB_PLANT_TYPE = "tbl_plant_type"
const DB_PLATFORM = "tbl_platform"
const DB_PROVINCE = "tbl_province"
const DB_ROLE = "tbl_role"
const DB_SCHEDULE = "tbl_schedule"
const DB_SENSOR = "tbl_sensor"
const DB_SENSOR_TYPE = "tbl_sensor_type"
const DB_SESSION_ACTION = "tbl_session_action"
const DB_SESSION_TIME = "tbl_session_time"
const DB_SOCKET = "tbl_socket"
const DB_STATUS = "tbl_status"
const DB_STATUS_SENSOR = "tbl_status_sensor"
const DB_SUB_DISTRICT = "tbl_sub_district"
const DB_TRANS_FERTILIZER_RATIO = "tbl_trans_fertilizer_ratio"
const DB_TRANS_MANAGEMENT = "tbl_trans_management"
const DB_TRANS_SCHEDULE_FARM = "tbl_trans_schedule_farm"
const DB_TRANS_SENSOR_VALUE_REC = "tbl_trans_sensor_value_rec"
const DB_TRANS_SOCKET_AREA = "tbl_trans_socket_area"
const DB_USERS = "tbl_users"
const DB_SOCKET_ACTION = "tbl_socket_action"
const DB_REMOTE_SWITCH = "tbl_tbl_remote_switch"
